sudo: required
dist: trusty
language: generic

install:
  - sudo apt-get install -qq -o=Dpkg::Use-Pty=0 python-software-properties
  - sudo add-apt-repository -o ppa:webupd8team/java
  - sudo apt-get update -qq -o=Dpkg::Use-Pty=0
  - sudo apt-get -y install -qq -o=Dpkg::Use-Pty=0 bison build-essential curl ccache flex lib32ncurses5-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev git-core make phablet-tools gperf openjdk-8-jdk

before_script:
  - git config --global user.name "jianminglok"
  - git config --global user.email "jianminglok@hotmail.com"
  - git config --global color.ui true
  - sudo chmod -R 777 build.sh
  - ./build.sh

script:
  - source build/envsetup.sh
  - breakfast kenzo
  - make bacon -j16
